Repository Evarisk/Saturne, pull requests merged in 2023-08, with the labels that each got.

#585 #584 [Trad] add: missing trad
  langs/fr_FR/saturne.lang
Labels: 0, Translation

#587 #586 [Document] add: hook saturneBuildDoc for document action
  core/tpl/documents/documents_action.tpl.php
Labels: 1, Enhancement

#593 #592 [SaturneObject] add: change update status deleted
  class/saturneobject.class.php
Labels: 1, Enhancement

#595 #594 [Media] add: saturne_get_media_linked_element function
  lib/medias.lib.php
Labels: 3, Enhancement

#600 #597 [Lib] add: manage extrafields in saturne_fetch_all_object_type
  lib/object.lib.php
Labels: 2, Enhancement

#599 #598 [SaturneObject] add: parameter addLabel getNomUrl
  class/saturneobject.class.php
Labels: 1, Enhancement

#603 #602 [Public] fix: fatal access with multicompany and not login
  core/tpl/attendants/attendants_table_view.tpl.php
  public/signature/add_signature.php
  view/saturne_attendants.php
Labels: 2, Bug

#608 #589 [Core] fix: dolibarr friendly object instanciation
  admin/object.php
  public/signature/add_signature.php
  view/saturne_agenda.php
  view/saturne_attendants.php
  view/saturne_document.php
  view/saturne_note.php
  view/saturne_schedules.php
Labels: 1, Enhancement

#612 #611 [Medias] fix: instanciation class for underscore classes
  core/tpl/medias/medias_gallery_modal.tpl.php
  lib/medias.lib.php
Labels: 1, Bug

#607 #606 [ODT] add: attendant job and company in odt
  core/modules/saturne/modules_saturne.php
Labels: 1, Enhancement

#616 #615 [Class] fix: remove typage on $ismultientitymanaged
  class/saturnecertificate.class.php
  class/saturnedashboard.class.php
  class/saturnedocuments.class.php
  class/saturneobject.class.php
  class/saturneschedules.class.php
  class/saturnesignature.class.php
  class/task/saturnetask.class.php
  core/modules/saturne/modules_saturne.php
Labels: 1, Bug

#620 #619 [Lib] fix: require_object_mod function
  class/saturneobject.class.php
Labels: 2, Bug

#626 #609 [MediaGallery] add: filters
  core/tpl/medias/medias_gallery_modal.tpl.php
  js/modules/mediaGallery.js
  js/saturne.min.js
  langs/fr_FR/medias.lang
  lib/medias.lib.php
Labels: 3, Enhancement

#625 #624 [Trad] add: new object action translation
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 0, Translation

#628 #627 [Media] fix: missing else for className instanciation
  core/tpl/medias/medias_gallery_modal.tpl.php
Labels: 0, Bug

#631 #630 [Core] fix: notice module updated
  core/tpl/index/index_view.tpl.php
Labels: 1, Bug

#636 #635 [MediasGallery] fix: missing include and form instanciation
  core/tpl/medias/medias_gallery_modal.tpl.php
  lib/medias.lib.php
Labels: 1, Bug

#641 #638 [Core] add: digirisk mention in mod
  core/modules/modSaturne.class.php
Labels: 0, Enhancement

#633 #632 [Class] fix: dolibarr 18 typage
  class/saturnecertificate.class.php
Labels: 0, Bug
