Repository Evarisk/Saturne, pull requests merged in 2023-09, with the labels that each got.

#653 #652 [Medias] fix: class instanciation for unlink file
  core/tpl/medias/medias_gallery_modal.tpl.php
Labels: 0, Bug

#663 #661 [Img] fix: generic object
  img/formconfirm/object_classify.png
  img/formconfirm/object_draft.png
  img/formconfirm/object_validate.png
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 0, Enhancement

#644 #643 [IHM] add: use picto in tabmenu on phone
  lib/object.lib.php
  lib/saturne.lib.php
  lib/saturne_functions.lib.php
Labels: 2, Enhancement, IHM

#674 #671 [Trad] fix: change trad for accident investigation
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 0, Enhancement

#642 fix media gallery
  lib/medias.lib.php
Labels: 3, Enhancement

#673 #672 [Medias] fix: fatal dolibarr 16 missing function
  core/tpl/medias/medias_gallery_modal.tpl.php
  lib/medias.lib.php
Labels: 1, Bug

#677 #675 [Img] fix: change investigation formconfirm img
  img/formconfirm/object_classify.png
  img/formconfirm/object_draft.png
  img/formconfirm/object_validate.png
  img/formconfirm/object_version_draft.png
  img/formconfirm/object_version_validate.png
  img/formconfirm/object_version_versioning.png
Labels: 0, Enhancement

#634 #629 [Core] add: new version number 1.1.2
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0, Enhancement
