Repository Evarisk/Saturne, pull requests merged in 2023-11, with the labels that each got.

#554 #551 [SaturneCertificate] add: check fetchall status
  class/saturnecertificate.class.php
Labels: 1, Enhancement

#700 #695 [Code] fix: remove underscore management in files
  admin/object.php
  core/tpl/medias/medias_gallery_modal.tpl.php
  lib/medias.lib.php
  public/signature/add_signature.php
  view/saturne_agenda.php
  view/saturne_attendants.php
  view/saturne_document.php
  view/saturne_note.php
  view/saturne_schedules.php
Labels: 0, Enhancement

#566 #158 [Mod] add: admin info on modules and dev contributing
  admin/information.php
  eoxia_modules.md
  evarisk_modules.md
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
  lib/saturne.lib.php
  saturne_dev.md
Labels: 2, Documentation, Enhancement

#705 #704 [JS] add: function reloadField
  js/modules/utils.js
  js/saturne.min.js
Labels: 2, Enhancement, JS

#711 #702 [Code] add: getpost subaction
  view/saturne_attendants.php
  view/saturne_note.php
  view/saturne_schedules.php
Labels: 0, Enhancement

#712 #706 [Dashboard] fix: langs->trans useless
  class/saturnedashboard.class.php
Labels: 1, Bug

#713 #707 [Mod] add: EasyUrl to saturne
  core/modules/modSaturne.class.php
Labels: 1, Enhancement

#714 #708 [TPL] fix: document action missing global
  core/tpl/documents/documents_action.tpl.php
Labels: 0, Bug

#724 #365 [Documentation] fix: doc modules
  eoxia_modules.md
  evarisk_modules.md
Labels: 1, Documentation

#723 #722 [Core] fix: new version number 1.2.0
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0

#732 #729 - #731 [Signature] add: improve IHM/Workflow signature
  class/saturnesignature.class.php
  core/tpl/attendants/attendants_table_view.tpl.php
  core/tpl/signature/signature_view.tpl.php
  css/saturne.min.css
  css/scss/page/_signature.scss
  lib/saturne_functions.lib.php
Labels: 5, Enhancement
