Repository Evarisk/Saturne, pull requests merged in 2023-07, with the labels that each got.

#459 #458 [Tools] add: trad export data
  langs/fr_FR/saturne.lang
Labels: 0

#466 #465 [SaturneObject] add: getTriggerDescription generic function
  class/saturneobject.class.php
  langs/fr_FR/saturne.lang
Labels: 2, Enhancement

#460 #427 [Core] add: allow external users on saturne main
  lib/saturne_functions.lib.php
  saturne.main.inc.php
Labels: 1, Enhancement

#462 #461 [CSS] add: button orange
  css/saturne.min.css
  css/scss/modules/button/_colors.scss
  css/scss/variable/_colors.scss
Labels: 1, Enhancement

#464 #463 [SaturneDashboard] add: improve dashboard list
  class/saturnedashboard.class.php
Labels: 1, Enhancement

#468 #465 [Triggers] add: improve getTriggerDescription
  class/saturneobject.class.php
Labels: 1, Enhancement

#473 #472 [CSS] add: grid and fix width
  class/saturnedashboard.class.php
  css/saturne.min.css
  css/scss/modules/_modules.scss
  css/scss/modules/grid/_grid.scss
  css/scss/modules/grid/index.php
  css/scss/modules/table/_flex.scss
Labels: 1, Enhancement

#477 #476 [Trad] add: improve EnableSaturne trad
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
  langs/en_US/object.lang
  langs/en_US/saturne.lang
  langs/fr_FR/object.lang
  langs/fr_FR/saturne.lang
Labels: 0, Enhancement

#491 #480 [SaturneTask] fix: need $ismultientitymanaged for prevent fetchAll with all tasks
  class/task/saturnetask.class.php
Labels: 1, Bug

#492 #41 [JS] add: use single hidden input instead for manage modal options
  class/actions_saturne.class.php
  core/tpl/index/index_view.tpl.php
  core/tpl/signature/signature_view.tpl.php
  js/modules/mediaGallery.js
  js/modules/modal.js
  js/saturne.min.js
  public/signature/add_signature.php
Labels: 3, Enhancement, JS

#498 #496 [SaturneDashboard] add: check data
  class/saturnedashboard.class.php
Labels: 1, Enhancement

#497 Fix missing media conf
  admin/media_gallery.php
  core/modules/modSaturne.class.php
  core/tpl/medias/medias_gallery_modal.tpl.php
  lib/medias.lib.php
  lib/saturne.lib.php
  lib/saturne_functions.lib.php
Labels: 1

#500 #1176 [Signature] add: close button
  public/signature/add_signature.php
Labels: 1, Enhancement

#503 #441 [SaturneSignature] add: init fk_object to avoid fatal error
  class/saturnesignature.class.php
Labels: 0, Bug

#505 #504 [SaturneObject] fix: validate method conflict with triggers
  class/saturneobject.class.php
Labels: 1, Bug

#509 #68 [Core] add: 1.1.0 readME
  README.md
Labels: 0, Enhancement

#512 #68 [Mod] fix: conflict changelog with builder
  ChangeLog.md
  changelog.md
Labels: 0, Bug

#518 #516 [CI/CD] add: editor config file for match PSR-12 conventions
  .editorconfig
Labels: 1, Enhancement

#530 #529 [SaturneObject] fix: missing include
  class/saturneobject.class.php
Labels: 1, Bug

#531 #528 [ODT] add: document name parameter
  core/modules/saturne/modules_saturne.php
Labels: 0, Enhancement, ODT

#534 #524 [Menu] add: digiquali menu entries
  core/modules/modSaturne.class.php
Labels: 0, Enhancement

#535 #525 [MediaGallery] fix: module name remainder
  core/tpl/medias/medias_gallery_modal.tpl.php
Labels: 0, Enhancement

#533 #532 [Core] add: require generic numbering modules
  class/saturneobject.class.php
  core/tpl/medias/medias_gallery_modal.tpl.php
  lib/object.lib.php
  lib/saturne_functions.lib.php
Labels: 2, Enhancement

#527 #526 [Lib] add: function get_objects_metada
  lib/object.lib.php
Labels: 0, Enhancement

#519 #515 [SaturneDashboard] add: conf for disable trunc
  class/saturnedashboard.class.php
Labels: 1, Enhancement

#539 #538 [SQL] fix: backward compatibility signature role
  sql/update.sql
Labels: 1, Enhancement

#537 #536 [SaturneCertificate] add: improve and fix
  class/saturnecertificate.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
  langs/en_US/object.lang
  langs/en_US/saturne.lang
  langs/fr_FR/object.lang
  langs/fr_FR/saturne.lang
Labels: 3, Enhancement

#541 #540 [Mod] add: new version number 1.1.1
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0, Enhancement

#545 #542 [Trad] add: generic object trad
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 0, Enhancement

#546 #543 [SaturneDashboard] add: showlegend option config
  class/saturnedashboard.class.php
Labels: 0, Enhancement

#556 #555 [Lib] fix: fatal error caused by global variable
  class/saturneobject.class.php
  lib/object.lib.php
Labels: 3, Bug

#570 #568 [SaturneTask] fix: fatal error caused by case
  class/task/saturnetask.class.php
Labels: 1, Bug

#561 #558 [Triggers] fix: signature wrong name
  class/saturnesignature.class.php
  core/tpl/attendants/attendants_table_view.tpl.php
  view/saturne_attendants.php
Labels: 2, Bug

#553 #552 [Trad] add: signatory trad
  langs/en_US/saturne.lang
  langs/en_US/signature.lang
  langs/fr_FR/saturne.lang
  langs/fr_FR/signature.lang
Labels: 0, Enhancement, Translation

#567 #565 [ODT] add: delete signature temp
  core/modules/saturne/modules_saturne.php
Labels: 1, Enhancement

#576 #574 [Mod] fix: ODT conf and attendant number
  core/modules/saturne/modules_saturne.php
Labels: 2, Bug, ODT

#573 #572 [PublicSignature] add: check document_type variable and file exists
  public/signature/add_signature.php
Labels: 1, Enhancement

#577 #575 [PublicInterface] fix: ODT name conflict with object
  class/saturnedocuments.class.php
  public/signature/add_signature.php
Labels: 2, Bug

#583 #580 [MediaGallery] fix: call to saturne_require_object_mod
  core/tpl/medias/medias_gallery_modal.tpl.php
Labels: 1, Bug

#582 #581 [Document] fix: check model and move zone parameters
  core/tpl/documents/documents_action.tpl.php
Labels: 1, Bug
