Repository Evarisk/Saturne, pull requests merged in 2023-06, with the labels that each got.

#413 #412 [Lib] fix: display module picto instead of object fontawesome
  lib/saturne_functions.lib.php
Labels: 2, Bug

#389 #384 [SaturneNote] add: check object status for manage permissionnote
  view/saturne_note.php
Labels: 1, Enhancement

#390 #385 [SaturneDashboard] add: list management
  class/saturnedashboard.class.php
Labels: 3, Enhancement

#391 #386 [Lib] fix: missing check label value saturne_banner_tab
  lib/saturne_functions.lib.php
Labels: 1, Enhancement

#392 #387 [Lib] fix: saturne_select_dictionary selected value
  lib/saturne_functions.lib.php
Labels: 1, Enhancement

#394 #388 [Lib] fix: creation media with id 0
  core/tpl/medias/medias_gallery_modal.tpl.php
Labels: 1, Enhancement

#411 #295 [Core] add: const to handle svg file as images
  core/modules/modSaturne.class.php
  lib/medias.lib.php
Labels: 2, Enhancement

#403 #402 [SaturneAttendants] fix: display date tzuser and save in UTC
  core/tpl/attendants/attendants_table_view.tpl.php
  public/signature/add_signature.php
  view/saturne_attendants.php
Labels: 1, Bug

#418 #404 [adminConf] add: change value conf for DOCUMENT_MEDIA_VIGNETTE_USED
  admin/documents.php
Labels: 1, Enhancement

#417 #405 [SaturneAttendants] fix: missing parameters in url
  core/tpl/attendants/attendants_table_add_view.tpl.php
  core/tpl/attendants/attendants_table_view.tpl.php
  view/saturne_attendants.php
Labels: 2, Enhancement

#410 #409 [CSS] add: picto min css
  core/modules/modSaturne.class.php
  css/scss/modules/picto/_picto.min.css
Labels: 0, IHM

#420 #419 [TPL] add: conf check defined and wrong variable name and check global value
  core/modules/saturne/modules_saturne.php
  core/tpl/documents/documents_action.tpl.php
Labels: 2, Enhancement

#424 #423 [JS] add: improve modal JS
  js/modules/modal.js
  js/saturne.min.js
  package-lock.json
Labels: 2, Enhancement

#439 #438 [SaturneDashboard] fix: remove info-box-sm css error
  class/saturnedashboard.class.php
Labels: 0, Bug

#436 #372 [SQL] fix: missing update field attendance signature
  sql/update.sql
Labels: 0, Bug

#435 #430 [Attendants] fix: disable send mail if signature not null
  core/tpl/attendants/attendants_table_view.tpl.php
Labels: 0, Bug

#434 #433 [Tpl] add: parameters on ajax constant function
  core/tpl/admin/object/object_const_view.tpl.php
Labels: 0, Enhancement

#432 #422 [Lib] fix: saturneBannerTab show all projects
  lib/saturne_functions.lib.php
Labels: 0, Bug

#399 #398 [Triggers] fix: rename locked and archived
  class/saturneobject.class.php
  class/saturnesignature.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0, Enhancement

#440 #433 [Tpl] fix: define default value as we want
  core/tpl/admin/object/object_const_view.tpl.php
Labels: 1, Enhancement

#455 #454 [SaturneSignature] add: default empty value to avoid fatal error
  class/saturnesignature.class.php
Labels: 0, Bug
