Repository Evarisk/Saturne, pull requests merged in 2023-12, with the labels that each got.

#687 #686 [Documents] add: improve setAttendantsSegment
  core/modules/saturne/modules_saturne.php
Labels: 2, Enhancement

#734 #733 [Admin] add: config page for manage PWA
  admin/pwa.php
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 2, Enhancement

#736 #735 [SaturneSignature] fix: JS load signature modal
  core/tpl/attendants/attendants_table_view.tpl.php
  core/tpl/signature/signature_view.tpl.php
  js/modules/modal.js
  js/saturne.min.js
  view/saturne_attendants.php
Labels: 2, Bug

#740 #737 [Langs] add: clonecategories translation
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 0, Translation

#745 #744 [ODT] fix: generating document with custom mod require fail
  core/modules/saturne/modules_saturne.php
Labels: 1, Bug

#747 #746 [Attendants] fix: missing td on attendants_table_add and improve responsive
  core/tpl/attendants/attendants_table_add_view.tpl.php
  core/tpl/attendants/attendants_table_view.tpl.php
Labels: 1, Bug

#749 #748 [Schedules] fix: init problem when cloning tms
  class/saturneschedules.class.php
Labels: 0, Bug

#507 #506 [Hook] fix: camelCase instead of PascalCase
  admin/documents.php
  core/tpl/admin/object/object_const_view.tpl.php
  core/tpl/index/index_view.tpl.php
Labels: 0, Bug

#755 #754 [SaturneObject] fix: getTriggerDescription function
  class/saturneobject.class.php
Labels: 0, Enhancement

#766 #765 [Mod] fix: error modAgenda dependancies and lang file
  core/modules/modSaturne.class.php
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 0, Bug

#759 #758 [Admin] add: change start url pwa
  admin/pwa.php
Labels: 0, Enhancement

#756 #728 [Hook] fix: change category hook to adapt to every class & module
  class/actions_saturne.class.php
  core/modules/modSaturne.class.php
Labels: 3, Bug

#763 #760 #761 #762 [Lib] add: improve images functionnality
  lib/medias.lib.php
  lib/object.lib.php
  lib/saturne_functions.lib.php
Labels: 3, Enhancement

#769 #767 [Config] fix: display numberingModuleDet if object is a line
  core/tpl/admin/object/object_numbering_module_view.tpl.php
Labels: 0, Bug

#771 #768 [ODT] fix: setAttendantsSegment rework segment name
  core/modules/saturne/modules_saturne.php
Labels: 2, Bug

#774 #773 [Hook] fix: handle dolimeet category hook exception
  class/actions_saturne.class.php
  lib/object.lib.php
Labels: 0, Bug

#775 #770 [Mod] add: new version 1.2.1
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0, Enhancement

#779 #778 [Lib] add: saturne_banner_tab improve banner info
  lib/saturne_functions.lib.php
Labels: 2, Enhancement

#788 #787 [TPL] fix: revert because PHP 8 is forbidden right now
  core/tpl/admin/object/object_numbering_module_view.tpl.php
Labels: 0, Bug

#786 #785 [Attendant] fix: wrong nb email on signatory
  core/tpl/attendants/attendants_table_view.tpl.php
Labels: 1, Bug

#784 #776 [Attendant] add: improve email attendant
  langs/en_US/signature.lang
  langs/fr_FR/signature.lang
  view/saturne_attendants.php
Labels: 2, Enhancement

#790 #789 [SaturneSignature] add: checkSignatoryHasObject function
  class/saturnesignature.class.php
Labels: 2, Enhancement
