Repository Evarisk/Saturne, pull requests merged in 2023-05, with the labels that each got.

#317 #316 [PublicInterface] add: change directory for specimen
  public/signature/add_signature.php
Labels: 1, Enhancement

#319 #315 [TPL] add: confirm action TPL
  core/tpl/object/object_action_workflow.tpl.php
Labels: 2, Enhancement

#321 #314 [ODT] Rework doc write file generation
  core/modules/saturne/modules_saturne.php
Labels: 3, Enhancement

#320 #268 [SaturneObject] add: use SaturneObject on class
  class/saturnecertificate.class.php
  class/saturnedocuments.class.php
  class/saturneobject.class.php
  class/saturneschedules.class.php
  class/saturnesignature.class.php
Labels: 3, Enhancement

#327 #325 [TPL] add: extrafields TPL
  core/tpl/admin/object/object_extrafields_view.tpl.php
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 1, Enhancement

#329 #328 [Mod] add: new version number 1.1.0
  README.md
  core/modules/modSaturne.class.php
Labels: 0, Enhancement

#331 #330 [Lib] fix: change value trunc template name
  lib/documents.lib.php
Labels: 0, Bug

#333 #332 [SQL] add: backward SQL signature and documents
  sql/update.sql
Labels: 2, Enhancement

#336 #334 [Attendants] add: PublicInterface custom ODT choice
  class/saturnedocuments.class.php
  core/tpl/attendants/attendants_table_add_view.tpl.php
  core/tpl/attendants/attendants_table_view.tpl.php
  lib/object.lib.php
  public/signature/add_signature.php
  view/saturne_attendants.php
Labels: 2, Enhancement

#342 [Trad] fix: missing trad
  core/tpl/index/index_view.tpl.php
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 1, Enhancement, Translation

#350 #348 [Trad] fix: missing trad variable
  langs/en_US/signature.lang
  langs/fr_FR/signature.lang
  view/saturne_attendants.php
Labels: 1, Bug

#353 #352 [Trad] add: generic trad medias/object
  langs/en_US/medias.lang
  langs/en_US/object.lang
  langs/fr_FR/medias.lang
  langs/fr_FR/object.lang
Labels: 1, Translation

#356 #355 [Lib] add: anchor id in list_titre of saturne_show_document
  lib/documents.lib.php
Labels: 0, Enhancement

#351 #349 [Attendants] fix: fatal foreach on unset array
  core/tpl/attendants/attendants_table_add_view.tpl.php
  core/tpl/attendants/attendants_table_view.tpl.php
  view/saturne_attendants.php
Labels: 2, Bug

#362 #359 [View] fix: show default photo if there is one
  view/saturne_agenda.php
  view/saturne_attendants.php
  view/saturne_document.php
  view/saturne_note.php
Labels: 0, Bug

#380 #378 [SaturneObject] fix: typing error
  class/saturneobject.class.php
Labels: 0, Bug

#381 #379 [Admin] add: improve admin document for manage medias and const
  admin/about.php
  admin/documents.php
  admin/media_gallery.php
  admin/setup.php
  core/tpl/admin/object/object_const_view.tpl.php
  langs/en_US/medias.lang
  langs/en_US/saturne.lang
  langs/fr_FR/medias.lang
  langs/fr_FR/saturne.lang
Labels: 3, Enhancement

#393 #370 [SaturneAttendants] fix: empty value need to be array signatoriesByRole
  core/tpl/attendants/attendants_table_add_view.tpl.php
  core/tpl/attendants/attendants_table_view.tpl.php
  view/saturne_attendants.php
Labels: 3, Enhancement
