Repository Evarisk/Saturne, pull requests merged in 2023-04, with the labels that each got.

#255 [SaturneCertificate] add: saturneCertificate object
  class/saturnecertificate.class.php
  class/saturnesignature.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
  langs/fr_FR/saturne.lang
  sql/certificate/index.php
  sql/certificate/llx_saturne_object_certificate.key.sql
  sql/certificate/llx_saturne_object_certificate.sql
  sql/certificate/llx_saturne_object_certificate_extrafields.key.sql
  sql/certificate/llx_saturne_object_certificate_extrafields.sql
Labels: 5, Enhancement

#256 #225 [Admin] add: template admin object
  admin/object.php
  core/tpl/admin/object/object_const_view.tpl.php
  core/tpl/admin/object/object_numbering_module_view.tpl.php
Labels: 2, Enhancement

#258 #226 [Mod] add: ModeleNumRefSaturne class for manage all modRef
  core/modules/saturne/modules_saturne.php
Labels: 2, Enhancement

#259 #227 [Admin] add: about page rework
  admin/about.php
  lib/saturne.lib.php
Labels: 2, Enhancement

#260 #98 [SaturneObject] add: generic object extend commonObject
  class/saturneobject.class.php
Labels: 3, Enhancement

#261 #197 [Mod] add: use isModEnabled function instead of $conf
  class/saturneobject.class.php
  class/saturneschedules.class.php
  class/saturnesignature.class.php
  lib/saturne_functions.lib.php
Labels: 2, Enhancement

#262 [SaturneDocuments] add: object documents for saturne
  class/saturnedocuments.class.php
  sql/documents/index.php
  sql/documents/llx_saturne_object_documents.key.sql
  sql/documents/llx_saturne_object_documents.sql
Labels: 2, Enhancement

#264 [Admin] add: documents page for manage module documents
  admin/documents.php
  core/tpl/admin/object/object_document_model_view.tpl.php
Labels: 2, Enhancement

#265 #118 [Doc] add: improve documentation dev for use saturne
  saturne_dev.md
Labels: 2, Documentation, Enhancement

#266 #251 [Lib] add: banner tab projectid key check
  lib/saturne_functions.lib.php
Labels: 1, Enhancement

#267 #249 [Trad] add: rename right trad for prevent conflict with formconfirm trad
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 1, Enhancement

#263 [SaturneDasboard] add: dashboard object
  class/saturnedashboard.class.php
  core/tpl/index/index_view.tpl.php
  css/saturne.min.css
  css/scss/element/_dashboard-box.scss
  css/scss/element/_element.scss
  css/scss/element/index.php
  css/scss/style.scss
  js/modules/dashboard.js
  js/saturne.min.js
Labels: 5, Enhancement

#245 Add module size vignette
  core/tpl/medias/medias_gallery_modal.tpl.php
  langs/fr_FR/medias.lang
Labels: 2, Enhancement

#274 #253 [Signature] add: builddoc action for specimen public interface
  class/saturnecertificate.class.php
  class/saturnedocuments.class.php
  class/saturnesignature.class.php
  public/signature/add_signature.php
Labels: 2, Enhancement

#277 #275 [Lib] add: improve dictionary functions for manage position
  lib/saturne_functions.lib.php
Labels: 2, Enhancement

#278 #276 [SaturneAttendants] add: moreparam attendant_table_mode manage display mode attendants
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
  lib/object.lib.php
  view/saturne_attendants.php
Labels: 2, Enhancement, Rework

#282 #279 [Mod] fix: fatal cause typage function need object instead of commonObject
  core/modules/saturne/modules_saturne.php
Labels: 1, Bug

#272 #269 [Config] add: setup logo
  admin/object.php
Labels: 1, Enhancement

#283 #241 [Lib] fix: move check in end of foreach
  lib/medias.lib.php
Labels: 1, Bug

#273 #247 [SaturneSignature] fix: wrong module name on use SaturneSignature class
  class/saturnesignature.class.php
  lib/object.lib.php
  view/saturne_attendants.php
Labels: 1, Enhancement

#303 #287 [SaturneCertificate] add: missing field type
  class/saturnecertificate.class.php
  sql/certificate/llx_saturne_object_certificate.sql
Labels: 1, Enhancement

#304 #284 #288 [SaturneAttendants] add: rework for factorize code in tpl
  core/tpl/attendants/attendants_table_add _view.tpl.php
  core/tpl/attendants/attendants_table_view.tpl.php
  langs/en_US/signature.lang
  langs/fr_FR/signature.lang
  view/saturne_attendants.php
Labels: 3, Enhancement, Rework

#305 #294 [Admin] add: tpl admin object extrafields management
  admin/object.php
  core/tpl/admin/object/object_extrafields_view.tpl.php
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 2, Enhancement

#307 #306 [Admin] fix: do generic call instead of module functions call
  admin/documents.php
Labels: 1, Bug
