Repository Evarisk/Saturne, pull requests merged in 2024-10, with the labels that each got.

#1094 #1093 [CSS] add: template infobox
  class/saturnedashboard.class.php
  css/saturne.min.css
  css/scss/element/_dashboard-box.scss
  css/scss/modules/_modules.scss
  css/scss/modules/infobox/_infobox.scss
  css/scss/variable/_colors.scss
  css/scss/variable/_structure.scss
  js/modules/dashboard.js
  js/saturne.min.js
Labels: 3, Enhancement, Integration

#1096 #1095 [CSS] add: img css for remove unwanted property
  css/saturne.min.css
  css/scss/modules/picto/_picto.min.css
  css/scss/modules/picto/_picto.scss
Labels: 0, Enhancement

#1098 #1097 [JS] fix: manage help button on menu
  js/modules/menu.js
  js/saturne.min.js
Labels: 1, JS

#1099 #1084 [Media] fix: add file button fatal
  core/tpl/medias/medias_gallery_modal.tpl.php
Labels: 1, Bug

#1101 #1100 [ODT] fix: change redirect proke method
  core/tpl/documents/documents_action.tpl.php
Labels: 1, Bug

#1103 #1102 [Lib] add: parameter entity for showUrlOfLastGeneratedDocument
  class/saturnedocuments.class.php
Labels: 1, Enhancement

#1106 #1105 [DocumentAction] fix: infinite redirect when archive
  class/saturnedashboard.class.php
  core/tpl/documents/documents_action.tpl.php
Labels: 2, Bug

#1111 #1108 [Dashboard] fix: remove useless form for exportcsv and manage it with JS
  class/saturnedashboard.class.php
  core/tpl/actions/dashboard_actions.tpl.php
  js/modules/dashboard.js
  js/saturne.min.js
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 2, Enhancement

#1114 #1113 [SaturneObject] add: label on getNomUrlTooltip
  class/saturneobject.class.php
Labels: 1, Enhancement
