Repository Evarisk/Saturne, pull requests merged in 2024-03, with the labels that each got.

#828 #808 [Modules] fix: liste_modeles should also return int in case of error
  core/modules/saturne/index.php
  core/modules/saturne/modules_saturne.php
  lib/documents.lib.php
Labels: 0

#869 #868 [Lib] fix: fatal saturne_object_prepare_head with hook each other with moduleNameLowerCase
  lib/object.lib.php
Labels: 1, Bug

#860 #844 [ModStandardButton] fix: activate and desactivate buttons
  core/tpl/actions/admin_conf_actions.tpl.php
  core/tpl/admin/object/object_numbering_module_view.tpl.php
Labels: 3, Bug

#887 #886 [Mod] add: setCustomValue function for set prefix and suffix custom ref
  core/modules/saturne/modules_saturne.php
Labels: 1, Enhancement

#882 #881 [Class] fix: do not type fk_user_creat and fk_user_modif
  class/saturnecertificate.class.php
  class/saturnedocuments.class.php
  class/saturneschedules.class.php
Labels: 0, Bug

#885 #884 [Lib] fix: saturne_object_action_for_category and saturne_show_object_list_in_category function for manage categories hook
  class/actions_saturne.class.php
  lib/object.lib.php
Labels: 3, Bug

#862 #861 [dashboardClass] add: gauge in dashboard
  class/saturnedashboard.class.php
Labels: 1, Enhancement

#829 #796 [JS] add: media functions
  core/tpl/medias/media_editor_modal.tpl.php
  core/tpl/medias/medias_gallery_modal.tpl.php
  js/modules/media.js
  js/saturne.min.js
  lib/saturne_functions.lib.php
Labels: 8, Enhancement

#832 #650 [JS] add: rework public signature view and JS action
  .gitignore
  class/actions_saturne.class.php
  core/substitutions/functions_saturne.lib.php
  core/tpl/actions/signature_actions.tpl.php
  core/tpl/attendants/attendants_table_view.tpl.php
  core/tpl/medias/media_editor_modal.tpl.php
  core/tpl/public/index.php
  core/tpl/public/public_confirmation_view.tpl.php
  core/tpl/signature/public_signature_view.tpl.php
  core/tpl/signature/signature_view.tpl.php
  css/saturne.min.css
  css/scss/page/_page.scss
  css/scss/page/_public-card.scss
  css/scss/page/_signature.scss
  img/assets/pencil-alt-solid.svg
  img/assets/public-card-background.png
  js/modules/modal.js
  js/modules/signature.js
  js/modules/toolbox.js
  js/modules/utils.js
  js/saturne.min.js
  langs/en_US/saturne.lang
  langs/en_US/signature.lang
  langs/fr_FR/saturne.lang
  langs/fr_FR/signature.lang
  public/signature/add_signature.php
  view/saturne_attendants.php
Labels: 5, Enhancement, JS, Rework

#880 #826 [Trans] add: SocietyAttendants used in DoliMeet and Digiquali
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: Translation

#890 #889 [Lib] fix: improve saturne_get_object_metadata
  lib/object.lib.php
Labels: 1, Enhancement
