Repository Evarisk/Saturne, pull requests merged in 2024-05, with the labels that each got.

#922 #921 [Dashboard] add: basic colors of dolibarr on graph
  class/saturnedashboard.class.php
Labels: 0, Enhancement

#916 #911 [Dashboard] add: button export data to csv
  class/saturnedashboard.class.php
  class/task/saturnetask.class.php
  core/modules/modSaturne.class.php
  core/tpl/actions/dashboard_actions.tpl.php
  core/tpl/index/index_view.tpl.php
  js/modules/button.js
  js/saturne.min.js
Labels: 3, Enhancement

#926 #919 [Trigger] fix: use br like dolibarr and new user_id field
  class/saturneobject.class.php
Labels: 1, Enhancement

#931 #930 [Mod] fix: New version number 1.4.0
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0, Enhancement

#937 #936 [SaturneTask] add: hook for getNomUrl
  class/task/saturnetask.class.php
Labels: 0, Enhancement, Good first issue

#939 #938 [Admin] fix: rework specimen action and use reposition
  admin/documents.php
  class/saturnedocuments.class.php
  core/tpl/admin/object/object_document_model_view.tpl.php
  core/tpl/documents/documents_action.tpl.php
Labels: 3, Bug

#945 #943 [Dashboard] fix: define a color instead of leaving it empty
  class/saturnedashboard.class.php
Labels: 2, Bug

#944 #942 [mediaGallery] fix: confirmation box no button
  core/tpl/utils/confirmation_view.tpl.php
  js/modules/mediaGallery.js
  js/saturne.min.js
Labels: 1, Bug, JS

#941 #938 [MediaGallery] fix: rework action for update banner element
  core/tpl/medias/medias_gallery_modal.tpl.php
Labels: 2, Bug, JS

#953 #952 [Admin] fix: missing parameters url form action
  admin/pwa.php
Labels: 0, Bug
