Repository Evarisk/Saturne, pull requests merged in 2024-07, with the labels that each got.

#999 #998 [PWA] add: translations + view for config
  admin/pwa.php
Labels: 1, Enhancement

#1008 #1000 [TPL] fix: missing div fichecenter
  core/tpl/index/index_view.tpl.php
Labels: 1, Bug

#1010 #621 [Signature] add: job, civility and json fields
  class/saturnesignature.class.php
  sql/signature/llx_saturne_object_signature.sql
  sql/update.sql
Labels: 2, Data model, Enhancement

#1011 #1009 [Signature] add: view and rework getNomUrl to display frozen data
  class/saturnesignature.class.php
  core/tpl/attendants/attendants_table_view.tpl.php
  sql/signature/llx_saturne_object_signature.sql
  sql/update.sql
Labels: 2, Enhancement

#1020 #1019 [Mod] add: jshintrc config file for improve jslinter and best pratices
  .jshintrc
Labels: 1, Enhancement, JS

#1031 #1030 [CSS] add: pico lib
  css/pico.min.css
Labels: 0, Enhancement

#1033 #1032 [Trad] add: public interface trad
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 0, Enhancement, Translation

#1024 #1023 [lib] Remove: CSS in media container
  css/saturne.min.css
  css/scss/modules/medias/_actions.scss
  css/scss/modules/medias/_photo.scss
  lib/medias.lib.php
  package-lock.json
Labels: 1, Enhancement, Integration
