Repository Evarisk/Saturne, pull requests merged in 2024-02, with the labels that each got.

#834 #833 [Task] add: ptt.elementtype for version >18 dolibarr in projectdoc
  class/task/saturnetask.class.php
Labels: 0, Bug

#836 #835 [Documentation] add: example of commit picture in the doc
  img/example_of_commit.png
  saturne_dev.md
Labels: 0, Documentation

#837 #835 [Documentation] fix: example of commit picture in the doc
  saturne_dev.md
Labels: 0, Documentation

#839 #717 [Attendatnts table view] add: plus icon for dropdown
  core/tpl/attendants/attendants_table_view.tpl.php
Labels: 1, Enhancement, IHM

#848 #847 [SaturneDashboard] add: custom content and link option for the widgets
  class/saturnedashboard.class.php
Labels: 1, Enhancement

#831 #806 [Lib] fix: saturne_banner_tab now use moreParamBannerTab as param
  lib/saturne_functions.lib.php
Labels: 2, Enhancement

#852 #850 [Media] add: regenerate thumbs media action
  core/tpl/medias/medias_gallery_modal.tpl.php
  js/modules/mediaGallery.js
  js/saturne.min.js
  lib/medias.lib.php
Labels: 2, Enhancement

#859 #843 [Document] fix: check errors after next ref and display error
  core/modules/saturne/modules_saturne.php
Labels: 1, Bug

#858 #857 [SaturneDashboard] fix: bug on the moreparams
  core/tpl/index/index_view.tpl.php
Labels: 1, Bug
