Repository Evarisk/Saturne, pull requests merged in 2024-09, with the labels that each got.

#1075 #1074 [Module.md] fix: 404 on github links
  eoxia_modules.md
  evarisk_modules.md
Labels: 0, Bug

#1073 #856 [ObjectActions] add: doc creation when archive
  core/tpl/actions/object_workflow_actions.tpl.php
  core/tpl/documents/documents_action.tpl.php
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 2, Enhancement

#1076 Add doc creation archive
  admin/setup.php
  core/modules/modSaturne.class.php
  core/tpl/actions/object_workflow_actions.tpl.php
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 0, Enhancement

#1078 #1071 [Lib] fix: rename function/change parameter value and doc
  lib/saturne_functions.lib.php
Labels: 0, Bug

#1027 #1026 [JS] add: audio JS for manage recording
  .jshintrc
  css/saturne.min.css
  css/scss/modules/_modules.scss
  css/scss/modules/audio/_audio.scss
  css/scss/modules/audio/index.php
  js/modules/audio.js
  js/modules/notice.js
  js/saturne.min.js
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
  lib/saturne_functions.lib.php
Labels: 2, Enhancement, JS

#1079 #1077 [Notice] add: tranlation support and add id parameter on saturne show notice
  js/modules/audio.js
  js/modules/notice.js
  js/saturne.min.js
  lib/saturne_functions.lib.php
Labels: 1, Enhancement

#1083 #1082 [Admin] add: PWA link
  admin/pwa.php
Labels: 0, Enhancement

#1080 4091 [CSS] fix: put background white and fix image too big
  css/saturne.min.css
  css/scss/modules/patchnote/_patchnote.scss
Labels: 0, Enhancement

#1089 #1088 [Mod] add: function check_variable for tpl
  core/tpl/admin/object/object_numbering_module_view.tpl.php
  core/tpl/utils/saturne_check_variable.php
Labels: 2, Enhancement
