Repository Evarisk/Saturne, pull requests merged in 2024-08, with the labels that each got.

#1037 #1032 [Trad] add: object trad
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 0, Enhancement, Translation

#1036 #1035 [Lib] fix: warning strpos
  core/tpl/documents/documents_action.tpl.php
  lib/documents.lib.php
Labels: 1, Bug

#1039 #1038 [SaturneDashboard] fix: widget content check
  class/saturnedashboard.class.php
Labels: 1, Bug

#1049 #1048 [Trad] add : rôle trad
  langs/fr_FR/signature.lang
Labels: 0, Enhancement

#1044 #962 [AttendantsTable] add: remove label "Participants -"
  core/tpl/attendants/attendants_table_view.tpl.php
Labels: 0, Enhancement

#1057 #1043 [Mod] add: gmao module link
  core/modules/modSaturne.class.php
Labels: 0, Enhancement

#1017 #948 [Documents / JS] fix: fatale on anchor
  admin/documents.php
  js/modules/toolbox.js
  js/saturne.min.js
Labels: 1, Bug, JS

#1062 #1061 [SaturnMedia] fix : fix multi picture delete on cancel
  js/modules/mediaGallery.js
  js/saturne.min.js
Labels: 1

#1063 #1032 [Trad] add: index trad and fix js
  js/modules/utils.js
  js/saturne.min.js
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 1, Translation, JS

#1065 #1064 [Mod] add: new version number 1.6.0
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
  js/saturne.min.js
Labels: 0, Enhancement

#1056 #3961 [JS / SaturneMedia] fix : fix image update when changed
  js/modules/mediaGallery.js
  js/saturne.min.js
  package-lock.json
Labels: 2, Bug

#1069 #1022 [Confirmbox] add : adding close button on confirm box
  core/tpl/utils/confirmation_view.tpl.php
  css/saturne.min.css
  css/scss/modules/card-confirmation/_card-confirmation.scss
  js/modules/keyEvents.js
  js/saturne.min.js
Labels: 1, Bug
