Repository Evarisk/Saturne, pull requests merged in 2024-04, with the labels that each got.

#879 #874 [Documents] add: config to add custom model
  admin/documents.php
  class/saturnedocuments.class.php
  core/modules/saturne/modules_saturne.php
  core/tpl/admin/object/object_document_model_view.tpl.php
  js/modules/document.js
  js/saturne.min.js
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
  lib/documents.lib.php
Labels: 3, Enhancement

#891 #863 [ODT] fix: new exception OdfExceptionSegmentNotFound and remove version attribute and phpmin
  core/modules/saturne/modules_saturne.php
  public/signature/add_signature.php
Labels: 2, Bug

#893 #892 [JS] add: improve canvas size and use conf for manage fast upload
  admin/setup.php
  core/tpl/medias/media_editor_modal.tpl.php
  core/tpl/medias/medias_gallery_modal.tpl.php
  js/modules/media.js
  js/saturne.min.js
  langs/en_US/saturne.lang
  langs/fr_FR/saturne.lang
Labels: 2, Enhancement, JS

#895 #888 [Mod] add: new version number 1.3.0
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
  js/saturne.min.js
Labels: 0, Enhancement

#899 #898 [Lib] fix: saturne_get_object_metadata should not replace filled…
  lib/object.lib.php
Labels: 0, Bug

#906 #905 [SaturneObject] add: getKanbanView function
  class/saturneobject.class.php
Labels: 2, Bug

#908 #907 [CSS / lib] add: moreCSS on grah and join and in object lib
  class/saturnedashboard.class.php
  css/saturne.min.css
  css/scss/modules/utils/_utils.scss
  lib/object.lib.php
Labels: 1, Enhancement

#910 [SaturneDocument] add: manage document type fields
  class/saturnedocuments.class.php
  core/modules/saturne/modules_saturne.php
Labels: 2, Enhancement

#915 #914 [SaturneDashboard] add: improve dashboard list
  class/saturnedashboard.class.php
Labels: 1, Enhancement
