Repository Evarisk/Saturne, pull requests merged in 2024-12, with the labels that each got.

#1133 #1125 [Lib] add: saturne_manage_extrafiels
  class/saturnedashboard.class.php
  class/saturneobject.class.php
  lib/saturne_functions.lib.php
Labels: 3, Enhancement

#1134 #1125 [Lib] fix: params saturne_manage_extrafiels
  lib/saturne_functions.lib.php
Labels: 1, Bug

#1136 #1135 [CSS] fix: include flexbox to css
  css/saturne.min.css
  css/scss/modules/_modules.scss
  css/scss/modules/flexbox/_flexbox.scss
Labels: 1

#1139 #1125 [Lib] fix: saturne_manage_extrafiels
  langs/fr_FR/signature.lang
  lib/saturne_functions.lib.php
Labels: 1, Bug

#1138 #1137 [Dashboard] add: total in dashboard list
  class/saturnedashboard.class.php
Labels: 1, Enhancement
