Repository Evarisk/Saturne, pull requests merged in 2024-06, with the labels that each got.

#951 #947 [Lib] fix: repair custom doc generation with corrupted key
  core/tpl/documents/documents_action.tpl.php
  lib/documents.lib.php
Labels: 2, Bug

#954 #949 [Medias] add: confirm box on unlink file
  js/modules/mediaGallery.js
  js/saturne.min.js
  langs/en_US/medias.lang
  langs/fr_FR/medias.lang
  lib/medias.lib.php
Labels: 1, Enhancement, JS

#957 #956 [Mod] add: new version number 1.5.0
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0, Enhancement

#976 #975 [Hook] fix: need change condition due to use strong hook like main
  class/actions_saturne.class.php
Labels: 1, Bug

#971 #970 [Class] fix: remove typage on $isextrafieldmanaged and resprints
  class/actions_saturne.class.php
  class/saturnecertificate.class.php
  class/saturnedocuments.class.php
  class/saturnemail.class.php
  class/saturneobject.class.php
  class/saturneschedules.class.php
  class/saturnesignature.class.php
Labels: 1, Bug

#967 #966 [JS] fix: menu wrong class name for target disabled
  js/modules/menu.js
  js/saturne.min.js
  package-lock.json
Labels: 0, Bug, JS

#987 #986 [SaturneDocumentModel] fix: use $this->module instead of GETPOST
  core/modules/saturne/modules_saturne.php
Labels: 1, Bug

#980 #979 [Document] add: use load_fiche_titre when no genallowed
  lib/documents.lib.php
Labels: 0, Enhancement

#985 #983 [Signature] fix: use normal cursor in read-only
  core/tpl/signature/public_signature_view.tpl.php
  css/saturne.min.css
  css/scss/page/_signature.scss
Labels: 1, Bug

#982 #981 [Medias] add: tooltip media from what translation
  langs/en_US/medias.lang
  langs/fr_FR/medias.lang
Labels: 0, Translation

#989 #988 [TPL] fix: generation document model conflict with custom name
  core/tpl/documents/documents_action.tpl.php
Labels: 1, Bug

#993 #960 [Category] fix: fatal navigation and improve check on className
  class/actions_saturne.class.php
  lib/object.lib.php
Labels: 1, Bug

#995 #994 [Mod] add: new version number
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0, Enhancement
