Repository Evarisk/Saturne, pull requests merged in 2024-01, with the labels that each got.

#792 #791 [TPL] add: mass action archive
  core/tpl/actions/list_massactions.tpl.php
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 2, Enhancement

#795 #793 [Lib] fix: customer is society for category
  lib/object.lib.php
Labels: 0, Bug

#799 #789 [SaturneSignature] fix: need filter for improve check
  class/saturnesignature.class.php
Labels: 1, Bug

#803 #802 [JS] add: manage object more infos
  js/modules/object.js
  js/saturne.min.js
Labels: 2, Enhancement, JS

#805 #804 [TPL] add: clean code for manage actions in action tpl
  core/tpl/actions/index.php
  core/tpl/actions/object_workflow_actions.tpl.php
Labels: 1, Enhancement, Rework

#798 #588 [Trigger] add: ip adress to signature and new actioncomm type
  class/saturneobject.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
  sql/data.sql
Labels: 2, Enhancement

#810 #809 [Hook] fix: category picto issue
  class/actions_saturne.class.php
Labels: 1, Bug

#812 #811 [Lib] add: saturne_create_category function
  lib/saturne_functions.lib.php
Labels: 3, Enhancement

#814 #813 [SaturneSignature] add: change function checkSignatoryHasObject
  class/saturnesignature.class.php
Labels: 1, Enhancement

#818 #815 [Substitution] add: saturne_completesubstitutionarray function for mail template
  core/modules/modSaturne.class.php
  core/substitutions/functions_saturne.lib.php
  core/substitutions/index.php
  img/object_saturne_color.png
  langs/en_US/signature.lang
  langs/fr_FR/signature.lang
  view/saturne_attendants.php
Labels: 2, Bug

#819 #770 [Mod] add: update release date
  README.md
Labels: 0, Enhancement

#817 #816 [JS] add: enforceMinMax js function
  js/modules/utils.js
  js/saturne.min.js
Labels: 2, Enhancement, JS

#825 #824 [Lib] fix: if field is empty check if object field is set
  lib/saturne_functions.lib.php
Labels: 1, Bug
