Repository Evarisk/Saturne, pull requests merged in 2025-02, with the labels that each got.

#1161 #1160 [Mod] add: new version number 1.7.0
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 1, Enhancement

#1157 #1156 [JS Toolbox] add: isphone function
  js/modules/toolbox.js
  js/saturne.min.js
Labels: 0, Enhancement

#1168 #1167 [MediasLib] fix: page slow saturne_get_media_linked
  lib/medias.lib.php
Labels: 3, Bug

#1170 #1169 [JS] add: function utils toggleSetting
  js/modules/utils.js
  js/saturne.min.js
Labels: 2, Enhancement, JS

#1175 #1174 [Mod] add: new version number 1.8.0
  README.md
  core/modules/modSaturne.class.php
  core/triggers/interface_99_modSaturne_SaturneTriggers.class.php
Labels: 0, Enhancement

#1179 #1178 [PublicSignature] fix: remove box when no object
  core/tpl/signature/public_signature_view.tpl.php
Labels: 0, Enhancement
