Repository Evarisk/Saturne, pull requests merged in 2025-08, with the labels that each got.

#1209 Fix documents name length limit
  lib/documents.lib.php
Labels: 2, Bug

#1231 #1230 [ODT] add signin session document
  documents/index.php
  documents/signinsheetdocument/index.php
  documents/signinsheetdocument/template_signinsheetdocument.odt
Labels: 1

#1235 #1234 [Dragable] add: cursor grab on dragable items
  css/saturne.min.css
  css/scss/components/_components.scss
  css/scss/components/_dragable.scss
  js/modules/dragable.js
  js/saturne.min.js
Labels: 0, Enhancement

#1239 #1238 [ObjectLib] fix: project task type fatal
  lib/object.lib.php
Labels: 1, Bug

#1241 #1240 [SaturneDashboard] add: half screen list dashboard
  class/saturnedashboard.class.php
Labels: 1
