Repository Evarisk/Saturne, pull requests merged in 2025-05, with the labels that each got.

#1196 #1195 [ODT] add: improve setTmpArrayVars with picto default value 0 and nocheck
  core/modules/saturne/modules_saturne.php
  lib/object.lib.php
Labels: 2, Enhancement

#1198 #1197 [TPL] add: action set_contract in banner_actions template
  core/tpl/actions/banner_actions.tpl.php
Labels: 0, Enhancement

#1182 #1085 [SaturneObject] add: rework fetch methods
  class/saturnemail.class.php
  class/saturneobject.class.php
  langs/en_US/object.lang
  langs/fr_FR/object.lang
Labels: 3, Enhancement, Rework

#1200 #1199 [JS] fix: use window.saturne.modal.loadLazyImages after all media gallery functions
  core/tpl/medias/medias_gallery_modal.tpl.php
  js/modules/mediaGallery.js
  js/modules/modal.js
  js/saturne.min.js
Labels: 2, Bug, JS
